apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKcFpXMWhabnBoYkdoaGMzTmhiaUlzSW1saGRDSTZNVGN6TWprNU5EazFPQ3dpWlhod0lqb3hOelkwTlRNd09UVTRMQ0poZFdRaU9pSjNkM2N1YVdWdFlXWjZZV3hvWVhOellXNHVkR1ZqYUNJc0luTjFZaUk2SW5CeWIycGxZM1JBWTJoaGRDMWhjSEF1WTI5dElpd2lSMmwyWlc1T1lXMWxJam9pYVdWdFlXWjZZV3dpTENKVGRYSnVZVzFsSWpvaWFHRnpjMkZ1SWl3aVJXMWhhV3dpT2lKamFHRjBZWEJ3UUdWNFlXMXdiR1V1WTI5dElpd2lVbTlzWlNJNld5SkVaWFpQY0hNZ1JXNW5hVzVsWlhJaUxDSlFjbTlxWldOMElFRmtiV2x1YVhOMGNtRjBiM0lpWFgwLjZxUnh4MXNEdjJvdFVrRHFHZFhIaFFGeWkySmlfRFNrdVpJMGpfV1VENXM=